Support named exports with nodejs ESM (#5162)
Summary:
It is currently not possible to use named exports with Relay in a Node.js ESM file. For example, in a brand new project with the latest version of relay-runtime as a dependency, the following code will error:

index.mjs:
```js filename="index.mjs"
import { fetchQuery } from 'relay-runtime'
```

```
file:///index.mjs:1
import { fetchQuery } from 'relay-runtime';
         ^^^^^^^^^^
SyntaxError: Named export 'fetchQuery' not found. The requested module 'relay-runtime' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'relay-runtime';
const { fetchQuery } = pkg;

    at #asyncInstantiate (node:internal/modules/esm/module_job:302:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:405:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:660:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
```

When an ESM file `import`s a common js file (like relay-runtime) Node.js will use [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer/tree/2.0.0) to try to determine compatible named exports.

[From the node.js docs](https://nodejs.org/api/esm.html):
> Named exports detection covers many common export patterns, reexport patterns and build tool and transpiler outputs. See [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer/tree/2.0.0) for the exact semantics implemented.

In the entry points of react-relay and relay-runtime, the pattern of exporting a property on another object causes `cjs-module-lexer` to not detect any of named exports.

Example:

```js
// This doesn't work
module.exports = {
  fetchQuery: RelayRuntime.fetchQuery
};

// This does work
const { fetchQuery } = RelayRuntime;
module.exports = {
  fetchQuery
};
```

In this PR, I updated the entrypoints of react-relay and relay-runtime to allow Node.js's cjs named export detection to work properly.  I added a test case to the Gulp build process since to test this we need the final transpiled code, but I am open to other approaches.

Pull Request resolved: https://github.com/facebook/relay/pull/5162

Reviewed By: evanyeung

Differential Revision: D99335902

Pulled By: captbaritone

fbshipit-source-id: 00d6f4fb36cdd97b0cafb4b46ec2fa6201ce4849