add option to `relay-compiler` to be quiet
Summary:
I have a project where I'm using [`relay-compiler-webpack`](https://github.com/danielholmes/relay-compiler-webpack-plugin) and am looking for ways for it to be a bit more quiet.

This patch removes the `console.log` calls from `CodeGenRunner.js` and replaces them with calls to a new method on the reporter `reportMessage` that checks the `quiet` option passed from the bin script before outputting to `stdout`.

Now I couldn't really test this since I couldn't get the build working so I would apprciate any help with that. I ran `npm run build` with `NODE_ENV` set to `production` so I could get the `bins` task to run since I was going to link the package into my project to see it working.

<details>

<summary>Build output</summary>

```
> relay@1.4.1 build /Users/koddsson/koddsson/relay
> gulp

[15:21:01] Using gulpfile ~/koddsson/relay/gulpfile.js
[15:21:01] Starting 'default'...
[15:21:01] Starting 'clean'...
[15:21:01] Finished 'clean' after 242 ms
[15:21:01] Starting 'copy-files'...
[15:21:01] Starting 'modules'...
[15:21:07] Finished 'copy-files' after 5.28 s

events.js:136
      throw er; // Unhandled 'error' event
      ^
Error: /Users/koddsson/koddsson/relay/packages/relay-compiler/node_modules/signal-exit/index.js: Cannot assign to a require(...) alias, EE. Line: 10.
    at PluginPass.Identifier (/Users/koddsson/koddsson/relay/node_modules/babel-preset-fbjs/plugins/inline-requires.js:119:17)
    at newFn (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/koddsson/koddsson/relay/node_modules/babel-traverse/lib/path/context.js:115:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! relay@1.4.1 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the relay@1.4.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/koddsson/.npm/_logs/2017-11-21T15_21_38_405Z-debug.log
```

</details>
Closes https://github.com/facebook/relay/pull/2204

Reviewed By: kassens

Differential Revision: D6831190

Pulled By: jstejada

fbshipit-source-id: b8c57b5dbfe7968a7dce2e531062a53cf76262b1