fix error message source location (#3745)
Summary:
Fixes https://github.com/facebook/relay/issues/3735

Diagnostic printer doesn't have access to the actual `line_index` and `column_index` from source files and operates only on extracted GraphQL text.

The simplest way to fix it is to change the `Sources` trait return type from `Option<String>` to `Option<GraphQLSource>`.

Implementation of diagnostic_reporter in `relay-lsp` is correct  and utilises source_reader, while `graphql-cli` doesn't have access to it. Maybe status_reporter in `relay-compiler` should be refactored to be more similar to `relay-lsp` and should contain its own implementation of diagnostic_reporter independent from `graphql-cli`.

This PR doesn't fix source location for the Validation message output:
```bash
 - Validation errors:
 - Variable was defined as type 'ID' but used where a variable of type 'ID!' is expected.:src/views/DataModel/components/ModelTreeDetails/ModelTreeDetails.tsx:63:66
```

Source fragment printed in `compile` method:
https://github.com/facebook/relay/blob/31c156a5658cd4360f0733e7213fea8c286b7627/compiler/crates/relay-compiler/src/compiler.rs#L157-L159
but Validation error is printed by macro and doesn't have access to the source_reader
https://github.com/facebook/relay/blob/31c156a5658cd4360f0733e7213fea8c286b7627/compiler/crates/relay-compiler/src/main.rs#L135-L137

Pull Request resolved: https://github.com/facebook/relay/pull/3745

Test Plan:
With this change the output has the correct line:

```
[INFO] querying files to compile...
[INFO] [default] compiling...
[ERROR] ✖︎ The type `User` has no field `asdd`.

  apps/frontend/pages/index.tsx:8:11
    7 │         user(id: $userId) {
    8 │           asdd
      │           ^^^^
    9 │           id

[ERROR] Compilation failed.
```

Before this change:
- error printed twice, both errors don't have the correct/human-readable line in the output.

```
[INFO] querying files to compile...
[INFO] [default] compiling...
[ERROR] ✖︎ The type `User` has no field `asdd`.

  apps/frontend/pages/index.tsx:4:11
    3 │         user(id: $userId) {
    4 │           asdd
      │           ^^^^
    5 │           id

[ERROR] Compilation failed.
[ERROR] Failed to build:
 - Validation errors:
 - The type `User` has no field `asdd`.:apps/frontend/pages/index.tsx:82:86

```

This also fixed error output in the internal version:
With this change (correct line in the test file):
```
querying files to compile...
[tests] compiling...
[ERROR] ✖︎ The type `FriendsEdge` has no field `asdasd`.

  relay-runtime/store/__tests__/RelayReader-test.js:182:13
  181 │             }
  182 │             asdasd
      │             ^^^^^^
  183 │           }

[ERROR] Compilation failed.
```

Before:
```
querying files to compile...
[tests] compiling...
[ERROR] ✖︎ The type `FriendsEdge` has no field `asdasd`.

  relay-runtime/store/__tests__/RelayReader-test.js:13:13
   12 │             }
   13 │             asdasd
      │             ^^^^^^
   14 │           }

[ERROR] Compilation failed.
```

Reviewed By: kassens

Differential Revision: D33568249

Pulled By: alunyov

fbshipit-source-id: cc659c5dc2622208d755c0dbf55b7407e8386d28