Respect excludes when using glob (#3688)
Summary:
My personal project's CI environment does not use watchman, and I run the compiler there to enforce codegen is up-to-date. Since watchman is unavailable, it falls back to glob mode which then fails due to files that can't be parsed by the compiler: (output slightly modified)

```
$ relay-compiler relay.config.json
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-interface/src/__tests__/__queries__/testQuery.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-interface/src/__tests__/__schema__/HoverTestSchema.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-interface/src/__tests__/__schema__/StarWarsSchema.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-interface/src/__tests__/kitchen-sink.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-interface/src/__tests__/queries/definitionQuery.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-interface/src/__tests__/queries/testQuery.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/graphql-language-service-utils/src/__tests__/__schema__/StarWarsSchema.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/codemirror-graphql/src/__tests__/kitchen-sink.graphql`: Expected *.graphql file to be either a schema or extension..
[WARN] Unexpected error in file categorizer for file `js/node_modules/codemirror-graphql/src/__tests__/schema-kitchen-sink.graphql`: Expected *.graphql file to be either a schema or extension..
Error:  Failed to read file: `/home/runner/work/mypriject/myproject/js/node_modules/hpack.js`.
Error:  Compilation failed.
Error:  Failed to read file: `/home/runner/work/myproject/myproject/js/node_modules/hpack.js`.
```

In this case, I believe the problem is that `hpack.js` is actually a directory and I had to manually set `excludes` in my Relay compiler config so I think there are 3 bugs here:
1. glob mode ignores `excludes`
2. the default for excludes (`"**/node_modules/**, "**/__mocks__/**", "**/__generated__/**"`) may be ignored right now (see below)
3. Broken attempt to read a directory that ends as a source suffix (`.js`) as a file

RE (2): My reading of the code is that perhaps in all modes the default for `excludes` is not set, it just happens that my `.watchmanconfig` has an exclude for `node_modules` so this hasn't happened for me yet (and AFAIK at Meta all environments where Relay would run have watchman around, or tests that mock it). I couldn't get my fix in this PR to work until I manually set `excludes` in the compiler's JSON config file. I guess I could remove the exclude from my `.watchmanconfig` but my laptop fans don't like it when I do that for my personal project, and I don't have the bandwidth to set up a test project just to confirm this theory since I don't know enough about Relay to fix it.

In this PR I fix (1). I don't have the skill with rust to figure out what's wrong with (2) or if it is indeed a bug (see above) and I'm not sure if (3) should be fixed (I lean towards yes but this might induce a costly perf hit that is unacceptable).

I'm happy to file Issues for (2) and (3) if that's the right thing to do. I'm interested in honing my Rust skills so, with some guidance, I'd be happy to help out with (2) and (3) if possible!

Pull Request resolved: https://github.com/facebook/relay/pull/3688

Test Plan:
Manual test run of the compiler on a personal project:
`FORCE_NO_WATCHMAN=1 cargo run --bin relay -- ../../../myproject/js/relay.config.json`

Reviewed By: alunyov

Differential Revision: D33054081

Pulled By: bigfootjon

fbshipit-source-id: 05f44f806b4e0dcba93084a95e2cdb84b1c31e7d