bump flatbuffer max tables to allow parsing large schemas
Summary:
When we try to collect the graphql schema info to inject it into our static analysis, it fails due to a flatbuffer limit on the max number of tables. https://fburl.com/k61k0kud

```
RUST_BACKTRACE=1 fbpython fbcode/graphql_build_infra/lite_executables/privacy_awareness_info/run_for_platform.py --out /tmp/after --platform fbandroid

...

thread 'main' panicked at fbcode/relay/oss/crates/schema/src/flatbuffer.rs:68:54:
Failed to get root as schema: TooManyTables
stack backtrace:
   0: __rustc::rust_begin_unwind
             at ./xplat/rust/toolchain/sysroot/1.87.0/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at ./xplat/rust/toolchain/sysroot/1.87.0/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at ./xplat/rust/toolchain/sysroot/1.87.0/library/core/src/result.rs:1704:5
   3: <schema::flatbuffer::FlatBufferSchema>::build
             at ./xplat/rust/toolchain/sysroot/1.87.0/library/core/src/result.rs:1061:23
   4: <schema::flatbuffer::wrapper::ouroboros_impl_owned_flat_buffer_schema::OwnedFlatBufferSchema>::new::<<schema::flatbuffer::wrapper::SchemaWrapper>::from_vec::{closure#0}>
             at ./fbcode/relay/oss/crates/schema/src/flatbuffer/wrapper.rs:94:36
   5: <schema::flatbuffer::wrapper::SchemaWrapper>::from_vec
             at ./fbcode/relay/oss/crates/schema/src/flatbuffer/wrapper.rs:45:1
   6: schema::build_schema_with_flat_buffer
             at ./fbcode/relay/oss/crates/schema/src/lib.rs:161:27
   7: <global_context::global_context::GlobalContextBuilder>::build
             at ./fbcode/graphql_build_infra/global_context/src/global_context.rs:44:17
   8: privacy_awareness_info::main
             at ./fbcode/graphql_build_infra/lite_executables/privacy_awareness_info/src/main.rs:37:26
```

Bump the default max tables to allow the script to continue.

 Use custom verifier options with increased max_tables limit (default 1M) to allow handling of large schemas

Reviewed By: cfsmp3

Differential Revision: D78012208

fbshipit-source-id: f47a01e545060fcb333651b0f354daddf54103d5