Skip importing export types in TS (#4754)
Summary:
A fix for a typescript generation bug discovered from the work in https://github.com/facebook/relay/issues/4753, with efforts to enable checking for all TS generated files https://github.com/facebook/relay/issues/4745

This fixes a class of Typescript errors in generated typescript files with TS checking enabled:
```
/src/__generated__/mutation.graphql.ts(11,27): error TS2305: Module '"relay-runtime"' has no exported member 'Mutation'.
/src/__generated__/mutation.graphql.ts(11,27): error TS6133: 'Mutation' is declared but its value is never read.
```

The root cause is the exported type is both not exported by the TS types, and not used due to typescript using the `export default` syntax.
Where flow would generate the following export:
```
module.exports = ((node/*: any*/)/*: Mutation<
  validateMutationTest9ChangeNameIncludeMutation$variables,
  validateMutationTest9ChangeNameIncludeMutation$data,
>*/);
```
Typescript would generate the following, not using the `Mutation` type:
```
export default node;
```

This fix removes the extraneous import type when the language is set as typescript.

Pull Request resolved: https://github.com/facebook/relay/pull/4754

Differential Revision: D60604034

fbshipit-source-id: f38fc80bba3b549a22ebbca544dca1f9e940cce0