Upgrade rustix to prevent build error (#4312)
Summary:
Currently the compiler build is failing in GitHub CI with the following error:

```
error[E0425]: cannot find function `makedev` in module `c`
  --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.37.3/src/backend/libc/fs/makedev.rs:44:17
   |
44 |     unsafe { c::makedev(maj as i32, min as i32) }
   |                 ^^^^^^^ not found in `c`
   |
help: consider importing this function
   |
2  | use crate::fs::makedev;
   |
help: if you import `makedev`, refer to it directly
   |
44 -     unsafe { c::makedev(maj as i32, min as i32) }
44 +     unsafe { makedev(maj as i32, min as i32) }
   |
```

Update done with:

```
cargo update -p rustix@0.37.3 --precise 0.37.19
```

I'm not entirely sure what in this upgrade is resolving the error, but it does seem to resolve it locally. Will check CI on this PR to confirm it fixes it in CI as well.

Pull Request resolved: https://github.com/facebook/relay/pull/4312

Test Plan: Confirmed that GitHub CI build steps that require building the compiler are green after this change: https://github.com/facebook/relay/actions/runs/4941621575/jobs/8834413135?pr=4312

Reviewed By: voideanvalue

Differential Revision: D45752364

Pulled By: captbaritone

fbshipit-source-id: 35ff8d6471210e44c9e541fdbcb3bf92ea5d0ee5