Fix Cargo build issues on main (#4614)
Summary:
I looks like compiler build is failing on main with the error:

```
error: failed to select a version for `version_check`.
    ... required by package `ahash v0.8.6`
    ... which satisfies dependency `ahash = "^0.8.6"` of package `hashbrown v0.14.3`
    ... which satisfies dependency `hashbrown = "^0.[14](https://github.com/facebook/relay/actions/runs/7839712944/job/21393173790#step:4:15).0"` (locked to 0.14.3) of package `dashmap v5.5.3`
    ... which satisfies dependency `dashmap = "^5.5.3"` (locked to 5.5.3) of package `graphql-ir-validations v0.0.0 (/home/runner/work/relay/relay/compiler/crates/graphql-ir-validations)`
    ... which satisfies path dependency `graphql-ir-validations` (locked to 0.0.0) of package `relay-transforms v0.0.0 (/home/runner/work/relay/relay/compiler/crates/relay-transforms)`
    ... which satisfies path dependency `relay-transforms` (locked to 0.0.0) of package `dependency-analyzer v0.0.0 (/home/runner/work/relay/relay/compiler/crates/dependency-analyzer)`
    ... which satisfies path dependency `dependency-analyzer` (locked to 0.0.0) of package `relay-compiler v0.0.0 (/home/runner/work/relay/relay/compiler/crates/relay-compiler)`
    ... which satisfies path dependency `relay-compiler` (locked to 0.0.0) of package `relay v[16](https://github.com/facebook/relay/actions/runs/7839712944/job/21393173790#step:4:17).2.0 (/home/runner/work/relay/relay/compiler/crates/relay-bin)`
versions that meet the requirements `^0.9.4` are: 0.9.4

all possible versions conflict with previously selected packages.

  previously selected package `version_check v0.9.2`
    ... which satisfies dependency `version_check = "^0.9"` (locked to 0.9.2) of package `proc-macro-error v1.0.4`
    ... which satisfies dependency `proc-macro-error = "^1"` (locked to 1.0.4) of package `clap_derive v3.2.25`
    ... which satisfies dependency `clap_derive = "=3.2.25"` (locked to 3.2.25) of package `clap v3.2.25`
    ... which satisfies dependency `clap = "^3.2.25"` (locked to 3.2.25) of package `fixture-tests v0.0.0 (/home/runner/work/relay/relay/compiler/crates/fixture-tests)`
    ... which satisfies path dependency `fixture-tests` (locked to 0.0.0) of package `dependency-analyzer v0.0.0 (/home/runner/work/relay/relay/compiler/crates/dependency-analyzer)`
    ... which satisfies path dependency `dependency-analyzer` (locked to 0.0.0) of package `relay-compiler v0.0.0 (/home/runner/work/relay/relay/compiler/crates/relay-compiler)`
    ... which satisfies path dependency `relay-compiler` (locked to 0.0.0) of package `relay v16.2.0 (/home/runner/work/relay/relay/compiler/crates/relay-bin)`

failed to select a version for `version_check` which could resolve this conflict
Error: Process completed with exit code 101.

```

To fix this, I just removed Cargo.lock and re-run the build locally - this detected a usage of a legacy method + updated the Cargo.lock file and resolved conflict in installed crates versions.

Pull Request resolved: https://github.com/facebook/relay/pull/4614

Reviewed By: alunyov

Differential Revision: D53613460

Pulled By: captbaritone

fbshipit-source-id: 41a196843639db9d796e17fcf79be61b5431595f