Revert Cargo.lock changes (#3458)
Summary:
It looks like babel update broke the compiler.

I'm working on releasing 11.0.2 and JS compiler is throwing on our Todo App

```
$ relay-compiler --src ./js/ --schema ./data/schema.graphql --artifactDirectory ./__generated__/relay
/Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:8004
var _createForOfIteratorHelper2 = _interopRequireDefault(__webpack_require__(4));
                                  ^

TypeError: _interopRequireDefault is not a function
    at Object.<anonymous> (/Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:8004:35)
    at __webpack_require__ (/Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:30:30)
    at Object.<anonymous> (/Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:7847:16)
    at __webpack_require__ (/Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:30:30)
    at /Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:94:18
    at Object.<anonymous> (/Users/alunyov/relay-examples/todo/node_modules/relay-compiler/bin/relay-compiler:97:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
error Command failed with exit code 1.

```

Pull Request resolved: https://github.com/facebook/relay/pull/3458

Test Plan:
- revert changes
- build relay
- compiler works in Todo App:
```
$ relay-compiler --src ./js/ --schema ./data/schema.graphql --artifactDirectory ./__generated__/relay
HINT: pass --watch to keep watching for changes.

Writing js
Unchanged: 12 files
{emoji:2728}  Done in 1.07s.

```

Reviewed By: kassens

Differential Revision: D27796554

Pulled By: alunyov

fbshipit-source-id: 55cdcc89612879457333d642848d78dfd06fb22a