Various fixes to make CI green again (#4464)
Summary:
- Added `babel-plugin-syntax-hermes-parser` to jest config to support new flow syntax
- Use `NO_COLOR` env variable to disable color printing in rust unit test after migration to tokio:test
- Backout `Build Compiler Explorer` https://github.com/facebook/relay/pull/3928 - this is currently failing with error:
```
Instruction does not dominate all uses!
  %143 = getelementptr inbounds %47, ptr %76, i32 0, i32 1, i32 1
  %137 = getelementptr inbounds %13, ptr %143, i32 0, i32 1
in function _ZN102_$LT$core..iter..adapters..map..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4fold17h3684d0946383414eE
LLVM ERROR: Broken function found, compilation aborted!
error: could not compile `schema` (lib)
warning: build failed, waiting for other jobs to finish...
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: cd "/Users/alunyov/relay/compiler/crates/relay-compiler-playground" && "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```
Need more time to investigate and fix it, but we want to unblock CI issues before the next release.

Pull Request resolved: https://github.com/facebook/relay/pull/4464

Reviewed By: captbaritone

Differential Revision: D49962335

Pulled By: alunyov

fbshipit-source-id: cfaf54e3d114fda49054583e73d2d12f10d89dc5